### ISSUE TITLE
Impossible ton install from October CMS

### ISSUE THREAD

**Issue by en-sz** [responsiv/pyrolancer-plugin#2]
When I try to install the plugin from October CMS, I get an error : 
"Cannot use object of type Illuminate\Http\Response as array" on BackendController.php line 80
TYPE
Undefined

EXCEPTION
Symfony\Component\Debug\Exception\FatalThrowableError

Is there any way to fix it ?

**Comment by daftspunk** [comment]
This looks like a problem unrelated to the plugin but related to a bug in the platform. It should get fixed soon in the later builds of October
