### ISSUE TITLE
Can not install from dashboard

### ISSUE THREAD

**Issue by shoxabbos** [responsiv/pyrolancer-plugin#4]
From here
![image](https://user-images.githubusercontent.com/8403807/69030554-b7993800-09f9-11ea-989c-5e7c37f8fb56.png)

**Comment by daftspunk** [comment]
What happens?

**Comment by shoxabbos** [comment]
Nothing. Does not show errors

**Comment by shoxabbos** [comment]
After installing the installed only two plagins RainLab: User & Location.

![image](https://user-images.githubusercontent.com/8403807/69035011-62aeef00-0a04-11ea-99d4-e56508fae92c.png)

**Comment by m49n** [comment]
> From here
> ![image](https://user-images.githubusercontent.com/8403807/69030554-b7993800-09f9-11ea-989c-5e7c37f8fb56.png)

You need to install user plus+
Pyrolancer required user plus+ -> user plus+ required reinlab.notify

I think it's worth adding a dependency Pyrolancer - rainlab.notify
